language: node_js

node_js:
  - "5"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - "npm config set spin false"
  - "npm --version"
  - "phantomjs --version"

install:
  - "npm install"

script:
  - npm test